export const CODE_BLACK_LANGUAGES = {
  js: 'JavaScript',
  jsx: 'JavaScript (JSX)',
  ts: 'TypeScript',
  tsx: 'TypeScript (TSX)',
  html: 'HTML',
  css: 'CSS',
  scss: 'SCSS',
  less: 'Less',
  json: 'JSON',
  yaml: 'YAML',
  xml: 'XML',
  markdown: 'Markdown',
  txt: 'Text',
  sql: 'SQL',
  graphql: 'GraphQL',
  bash: 'Bash',
  shell: 'Shell',
  python: 'Python',
  java: 'Java',
  kotlin: 'Kotlin',
  swift: 'Swift',
  c: 'C',
  cpp: 'C++',
  csharp: 'C#',
  go: 'Go',
  rust: 'Rust',
  php: 'PHP',
  ruby: 'Ruby',
  perl: 'Perl',
  lua: 'Lua',
  r: 'R',
  dart: 'Dart',
  scala: 'Scala',
  groovy: 'Groovy',
  objectivec: 'Objective-C',
  ocaml: 'OCaml',
  elixir: 'Elixir',
  erlang: 'Erlang',
  haskell: 'Haskell',
  clojure: 'Clojure',
  fsharp: 'F#',
  vb: 'Visual Basic',
  matlab: 'MATLAB',
  makefile: 'Makefile',
  dockerfile: 'Dockerfile',
  ini: 'INI',
  toml: 'TOML',
  powershell: 'PowerShell',
};
